- id: '1627594299059'
  alias: Living room shutdown
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 65ba194082c4a7958fd4458384de21a7
    entity_id: light.living_room_lamp
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: 7bdd071ef03c90a3a5a9a7ff0fd4dee5
    entity_id: switch.bsd29_1
    domain: switch
  mode: single
- id: '1627600265208'
  alias: Office startup
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 8c6cc3aa26363cdb6b84f6759afbd2fd
    entity_id: light.office_lamp
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: bf841bc35e5149cd8e33075fdfd07311
    entity_id: switch.bsd29_2
    domain: switch
  - type: turn_on
    device_id: 111c672dcd911159145b56bff87290a0
    entity_id: light.shelf_lighting_left
    domain: light
    brightness_pct: 100
  mode: single
- id: '1627669737153'
  alias: Office shutdown
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 8c6cc3aa26363cdb6b84f6759afbd2fd
    entity_id: light.office_lamp
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: bf841bc35e5149cd8e33075fdfd07311
    entity_id: switch.bsd29_2
    domain: switch
  - type: turn_off
    device_id: 8219482063c73b32176be61a20de405a
    entity_id: switch.bsd29_3
    domain: switch
  - type: turn_off
    device_id: ded7d0fc4f491c9b7572f031c5ee964b
    entity_id: light.keylight
    domain: light
  - type: turn_off
    device_id: 111c672dcd911159145b56bff87290a0
    entity_id: light.shelf_lighting_left
    domain: light
  mode: single
- id: '1627747019524'
  alias: Movie mode
  description: ''
  trigger:
  - platform: device
    device_id: a7e1920415c3bebeb0f583e67a0071ee
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: playing
  condition: []
  action:
  - scene: scene.movie_mode
  mode: single
- id: '1628161656228'
  alias: Desk button single tap
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:12:4b:00:22:cf:67:01
      command: toggle
  condition: []
  action:
  - type: toggle
    device_id: ded7d0fc4f491c9b7572f031c5ee964b
    entity_id: light.keylight
    domain: light
  mode: single
- id: '1629929229980'
  alias: Arrive home
  description: ''
  trigger:
  - platform: state
    entity_id: group.presence_home
    to: home
  condition: []
  action:
  - scene: scene.arrive_home
  - service: notify.mobile_app_pixel_5
    data:
      message: Arrived home
  mode: single
- id: '1629929297023'
  alias: Leave home
  description: ''
  trigger:
  - platform: state
    entity_id: group.presence_home
    to: not_home
  condition: []
  action:
  - scene: scene.leave_home
  - service: notify.mobile_app_pixel_5
    data:
      message: Home now empty
  mode: single
- id: '1630079032711'
  alias: Desk button double tap
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:12:4b:00:22:cf:67:01
      command: 'on'
  condition: []
  action:
  - type: toggle
    device_id: 8219482063c73b32176be61a20de405a
    entity_id: switch.bsd29_3
    domain: switch
  mode: single
- id: '1630698257803'
  alias: 'Bedroom dimmer: Brightness up'
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:09:a5:5a:4f
      command: up_press
  condition: []
  action:
  - device_id: 3a54b48bbfa668b4dd79ad4020264556
    domain: light
    entity_id: light.bedroom_lamp_left
    type: brightness_increase
  - device_id: 72123316443cca933eb72ca76045b099
    domain: light
    entity_id: light.bedroom_lamp_right
    type: brightness_increase
  mode: single
- id: '1630703068469'
  alias: 'Bedroom dimmer: Brightness down'
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:09:a5:5a:4f
      command: down_press
  condition: []
  action:
  - device_id: 3a54b48bbfa668b4dd79ad4020264556
    domain: light
    entity_id: light.bedroom_lamp_left
    type: brightness_decrease
  - device_id: 72123316443cca933eb72ca76045b099
    domain: light
    entity_id: light.bedroom_lamp_right
    type: brightness_decrease
  mode: single
- id: '1630703896513'
  alias: 'Bedroom dimmer: On'
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:09:a5:5a:4f
      command: on_press
  condition: []
  action:
  - type: turn_on
    device_id: 3a54b48bbfa668b4dd79ad4020264556
    entity_id: light.bedroom_lamp_left
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 72123316443cca933eb72ca76045b099
    entity_id: light.bedroom_lamp_right
    domain: light
    brightness_pct: 100
  mode: single
- id: '1630704252622'
  alias: 'Bedroom dimmer: Off'
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:09:a5:5a:4f
      command: off_press
  condition: []
  action:
  - type: turn_off
    device_id: 3a54b48bbfa668b4dd79ad4020264556
    entity_id: light.bedroom_lamp_left
    domain: light
  - type: turn_off
    device_id: 72123316443cca933eb72ca76045b099
    entity_id: light.bedroom_lamp_right
    domain: light
  mode: single
- id: '1630704669677'
  alias: Morning
  description: Turn on bedroom lights at 08:30, if anyone's home.
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: state
    entity_id: group.presence_home
    state: home
  action:
  - scene: scene.morning
  mode: single
