# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script ui: !include scripts.yaml

scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml
