- platform: generic_thermostat
  name: "Server cabinet"
  unique_id: server_cabinet
  heater: light.homelab_power_ventilation
  target_sensor: sensor.servers_sensor_temperature
  ac_mode: true
  initial_hvac_mode: "cool"

- platform: generic_thermostat
  name: "Router"
  heater: light.homelab_power_router_fan
  target_sensor: sensor.filtered_ucg_max_temperature
  cold_tolerance: 3
  hot_tolerance: 3
  ac_mode: true
  max_temp: 100
