- platform: generic_thermostat
  name: "Server cabinet"
  heater: switch.server_fans
  target_sensor: sensor.servers_sensor_temperature
  target_temp: 25
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  ac_mode: true
  initial_hvac_mode: "cool"
  min_cycle_duration:
    minutes: 5
