- platform: generic_thermostat
  name: "Server cabinet"
  heater: light.homelab_power_usb
  target_sensor: sensor.servers_sensor_temperature
  ac_mode: true
  initial_hvac_mode: "cool"
  min_cycle_duration:
    minutes: 5

- platform: generic_thermostat
  name: "Router"
  heater: light.homelab_power_router_fan
  target_sensor: sensor.filtered_ucg_max_temperature
  ac_mode: true
  max_temp: 100
  min_cycle_duration:
    minutes: 5
