- platform: generic_thermostat
  name: "Server cabinet"
  heater: light.homelab_power_usb
  target_sensor: sensor.servers_sensor_temperature
  ac_mode: true
  initial_hvac_mode: "cool"

- platform: generic_thermostat
  name: "Barn"
  heater: switch.barn_fan
  target_sensor: sensor.barn_sensor_temperature
  ac_mode: true

- platform: generic_thermostat
  name: "Router"
  heater: light.homelab_power_router_fan
  target_sensor: sensor.ucg_max_ucg_max_cpu_temperature
  ac_mode: true
  max_temp: 100
