# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards.yaml

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"

recorder:
  purge_keep_days: 60

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script ui: !include scripts.yaml

scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_6

ecovacs: !include ecovacs.yaml
