# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

adaptive_lighting: !include adaptive_lighting.yaml
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
climate ui: !include climate.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
rest_command: !include rest_command.yaml
scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml
schedule: !include schedules.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
template: !include template.yaml
timer: !include timer.yaml

command_line:
  - sensor:
      name: "Enphase JWT"
      command: "/config/scripts/get-enphase-token.sh"
      scan_interval: 900 # every 15 minutes
      value_template: "{{ value_json.status }}"
      json_attributes:
        - token
        - xsrf

  - sensor:
      name: "Enphase Schedules"
      command: >
        /bin/bash -c 'ENPHASE_AUTH="{{ state_attr("sensor.enphase_jwt", "token") }}"
        ENPHASE_XSRF="{{ state_attr("sensor.enphase_jwt", "xsrf") }}"
        /config/scripts/get_enphase_schedules_json.sh'
      scan_interval: 30
      value_template: "OK"
      json_attributes:
        - cfg
        - dtg
        - rbd
        - other

lovelace:
  mode: storage
  dashboards:
    home-page:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboard_sections.yaml
    plants-page:
      mode: yaml
      title: Plants
      icon: mdi:flower
      show_in_sidebar: true
      filename: dashboard_plants.yaml

logger:
  default: warning
  logs:
    # Disable noisy Ring integration logs:
    # WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
    ring_doorbell.doorbot: error

recorder:
  purge_keep_days: 60

# Text to speech
tts:
  - platform: google_translate

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_9

wake_on_lan:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8

# https://github.com/v6ak/v6-quietdrift
v6_quietdrift:

zha:
  custom_quirks_path: /config/zha_quirks/
