# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards.yaml

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"

recorder:
  purge_keep_days: 60

input_boolean:
  lighting_automations:
    name: Enable lighting automation
    initial: true
    icon: mdi:lightbulb-auto
  heating_automations:
    name: Enable heating automation
    initial: true
    icon: mdi:thermostat-auto

input_select:
  heating_mode:
    name: Heating mode
    options:
      - away
      - sleep
      - home
      - comfort
    icon: mdi:home-thermometer
  active_room:
    name: Active room
    options:
      - bedroom
      - office
      - living-room
    icon: mdi:door-sliding

shell_command:
  shutdown_sinkhole: 'ssh dan@10.10.10.50 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no "sudo poweroff"'

template:
  - binary_sensor:
      - name: "Off peak"
        icon: mdi:transmission-tower
        state: "{{states('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate') | float < 0.3}}"

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script ui: !include scripts.yaml

scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_6

climate: !include climate.yaml

schedule: !include schedules.yaml
