# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards.yaml

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"

recorder:
  purge_keep_days: 60

input_boolean:
  presence_automations:
    name: Enable presence-based automation
    initial: true
    icon: mdi:home-account
  heating_automations:
    name: Enable heating automation
    initial: true
    icon: mdi:thermostat-auto

input_select:
  heating_mode:
    name: Heating mode
    options:
      - away
      - sleep
      - home
      - comfort
    icon: mdi:home-thermometer

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script ui: !include scripts.yaml

scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_6

climate: !include climate.yaml

schedule: !include schedules.yaml
