# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

adaptive_lighting: !include adaptive_lighting.yaml
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
climate ui: !include climate.yaml
generic_hygrostat: !include generic_hygrostat.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
rest_command: !include rest_command.yaml
scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml
schedule: !include schedules.yaml
script: !include scripts.yaml
switch: !include switch.yaml
template: !include template.yaml
timer: !include timer.yaml

command_line:
  - sensor:
      name: BBC news
      command: curl -s https://www.bbc.co.uk/programmes/p002vsn1/episodes/player | grep '"@type":"RadioSeries"' | jq -r '.episode[0].url' | xargs curl -s | grep 'audio-nondrm-download/' | sed -n 's/.*href="\/\/\([^"]*\)".*/https:\/\/\1/p'

lovelace:
  mode: storage
  dashboards:
    home-page:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboard_sections.yaml

recorder:
  purge_keep_days: 60

shell_command:
  shutdown_sinkhole: 'ssh dan@10.10.10.50 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no "sudo poweroff"'
  shutdown_eden: 'ssh dan@10.10.10.51 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no "sudo poweroff"'
  shutdown_mele: 'ssh dan@10.10.10.60 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no "sudo poweroff"'

# Text to speech
tts:
  - platform: google_translate

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_8

wake_on_lan:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
