# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
climate: !include climate.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
sensor: !include sensor.yaml
scene manual: !include_dir_list scenes/
scene ui: !include scenes.yaml
schedule: !include schedules.yaml
script ui: !include scripts.yaml

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards.yaml

recorder:
  purge_keep_days: 60

shell_command:
  shutdown_sinkhole: 'ssh dan@10.10.10.50 -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no "sudo poweroff"'

template:
  - binary_sensor:
      - name: "Off peak"
        icon: mdi:transmission-tower
        state: "{{states('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate') | float < 0.3}}"

# Text to speech
tts:
  - platform: google_translate

notify:
  - platform: group
    name: dan
    services:
      - service: mobile_app_pixel_6

homeassistant:
  allowlist_external_dirs:
    - "/config"
