- platform: rest
  name: Tasmota latest release
  resource: https://api.github.com/repos/arendst/Tasmota/releases/latest
  value_template: "{{ value_json.tag_name }}"
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
