- platform: rest
  name: Tasmota latest release
  resource: https://api.github.com/repos/arendst/Tasmota/releases/latest
  value_template: "{{ value_json.tag_name }}"
  force_update: true
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor

- platform: rest
  name: ArchiveTeam contributions
  resource: https://legacy-api.arpa.li/reddit/stats.json
  value_template: "{{ value_json.downloader_count.d1ffidence }}"
  headers:
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
