- platform: template
  switches:
    barn_ac_power:
      friendly_name: "Barn AC Power"
      value_template: "{{ states('climate.barn_ac') in ['heat','cool','heat_cool','fan_only','dry'] }}"
      turn_on:
        service: climate.set_hvac_mode
        target:
          entity_id: climate.barn_ac
        data:
          hvac_mode: heat
      turn_off:
        service: climate.set_hvac_mode
        target:
          entity_id: climate.barn_ac
        data:
          hvac_mode: "off"
