- alias: "Bedroom dimmer: Toggle"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a5:5a:4f
        command: on_press
  action:
    service: light.toggle
    target:
      entity_id: group.bedroom_lights
- alias: "Bedroom dimmer: Up"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a5:5a:4f
        command: up_press
  action:
    service: light.turn_on
    target:
      entity_id: group.bedroom_lights
    data:
      brightness_step_pct: 20
- alias: "Bedroom dimmer: Down"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a5:5a:4f
        command: down_press
  action:
    service: light.turn_on
    target:
      entity_id: group.bedroom_lights
    data:
      brightness_step_pct: -20
- alias: "Bedroom dimmer: Off"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a5:5a:4f
        command: off_press
  action:
    service: light.turn_off
    target:
      entity_id: group.bedroom_lights
