- alias: "Bedroom dimmer: Up"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a5:5a:4f
        command: up_press
  action:
    - device_id: 3a54b48bbfa668b4dd79ad4020264556
      domain: light
      entity_id: light.bedroom_lamp_left
      type: brightness_increase
    - device_id: 72123316443cca933eb72ca76045b099
      domain: light
      entity_id: light.bedroom_lamp_right
      type: brightness_increase
