- alias: "Door: open"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  action:
    - service: notify.mobile_app_pixel_5
      data:
        message: Door open
- alias: "Door: closed"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "on"
      to: "off"
  action:
    - service: notify.mobile_app_pixel_5
      data:
        message: Door closed
