- alias: "Living room: Off"
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: 2460b267c6c74fe6156419f6d4e7b7d3
      entity_id: light.living_room_lamp
      domain: light
  action:
    - type: turn_off
      device_id: 7bdd071ef03c90a3a5a9a7ff0fd4dee5
      entity_id: switch.living_room_fan
      domain: switch
