- alias: "Living room dimmer: Toggle"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:b8:90
        command: on_press
  action:
    service: light.toggle
    target:
      entity_id: group.living_room_lights
- alias: "Living room dimmer: Double press"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:b8:90
        command: on_double_press
  action:
    service: switch.toggle
    target:
      entity_id: switch.living_room_fan
- alias: "Living room dimmer: Up"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:b8:90
        command: up_press
  action:
    service: light.turn_on
    target:
      entity_id: group.living_room_lights
    data:
      brightness_step_pct: 20
- alias: "Living room dimmer: Down"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:b8:90
        command: down_press
  action:
    service: light.turn_on
    target:
      entity_id: group.living_room_lights
    data:
      brightness_step_pct: -20
- alias: "Living room dimmer: Off"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:b8:90
        command: off_press
  action:
    - service: light.turn_off
      target:
        entity_id: group.living_room_lights
