- alias: Movie mode
  mode: single
  trigger:
    - platform: device
      device_id: a7e1920415c3bebeb0f583e67a0071ee
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: playing
  action:
    - scene: scene.movie_mode
