- alias: Office startup
  mode: single
  trigger:
    - platform: device
      type: turned_on
      device_id: 8c6cc3aa26363cdb6b84f6759afbd2fd
      entity_id: light.office_lamp
      domain: light
      for:
        seconds: 5
  action:
    - type: turn_on
      device_id: bf841bc35e5149cd8e33075fdfd07311
      entity_id: switch.pc_strip
      domain: switch
    - type: turn_on
      device_id: 111c672dcd911159145b56bff87290a0
      entity_id: light.shelf_lighting_left
      domain: light
      brightness_pct: 100
