- alias: "Office: desk button tap"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:12:4b:00:22:cf:67:01
        command: toggle
  action:
    service: light.toggle
    target:
      entity_id: group.balcony_lights
