- alias: "Office dimmer: Short-hold toggle"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:cf:36
        command: on_short_release
  action:
    service: light.toggle
    target:
      entity_id: light.office_lamp
- alias: "Office dimmer: Long-hold scene"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:cf:36
        command: on_long_release
  action:
    - scene: scene.office_daytime
- alias: "Office dimmer: Up"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:cf:36
        command: up_press
  action:
    service: light.turn_on
    target:
      entity_id: light.office_lamp
    data:
      brightness_step_pct: 20
- alias: "Office dimmer: Down"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:cf:36
        command: down_press
  action:
    service: light.turn_on
    target:
      entity_id: light.office_lamp
    data:
      brightness_step_pct: -20
- alias: "Office dimmer: Off"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:17:88:01:09:a6:cf:36
        command: off_press
  action:
    service: light.turn_off
    target:
      entity_id: light.office_lamp
