- alias: "Office: desk button double tap"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:12:4b:00:22:cf:67:01
        command: "on"
  action:
    - type: toggle
      device_id: 8219482063c73b32176be61a20de405a
      entity_id: switch.office_fan
      domain: switch
