- alias: Office shutdown
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: e3d8b13c22696666e740d69958c7584f
      entity_id: light.office_lamp
      domain: light
  action:
    - type: turn_off
      device_id: bf841bc35e5149cd8e33075fdfd07311
      entity_id: switch.bsd29_2
      domain: switch
    - type: turn_off
      device_id: 8219482063c73b32176be61a20de405a
      entity_id: switch.bsd29_3
      domain: switch
    - type: turn_off
      device_id: ded7d0fc4f491c9b7572f031c5ee964b
      entity_id: light.keylight
      domain: light
    - type: turn_off
      device_id: 111c672dcd911159145b56bff87290a0
      entity_id: light.shelf_lighting_left
      domain: light
