- alias: "Phone charger: On"
  mode: single
  trigger:
    - platform: time
      at: "01:00:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.phonecharger

- alias: "Phone charger: Off"
  mode: single
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.phonecharger
