- alias: "Power monitors: Always on"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - group.power_monitors
  action:
    - service: switch.turn_on
      target:
        entity_id: group.power_monitors
    - service: notify.dan
      data:
        message: Power monitor was off, restarted
