- alias: Leave home
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: home
      to: not_home
  action:
    - scene: scene.everything_off
    - service: notify.mobile_app_pixel_5
      data:
        message: Away mode
