- alias: "Arrive: lights"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: sun
      after: sunset
  action:
    - scene: scene.everything_on

- alias: "Arrive: notify"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  action:
    - service: notify.mobile_app_pixel_5
      data:
        message: Arrived home

- alias: Leave home
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: home
      to: not_home
  action:
    - scene: scene.everything_off
    - service: notify.mobile_app_pixel_5
      data:
        message: Away mode
