- alias: Morning
  description: Turn on bedroom lights at 08:30, if anyone's home.
  mode: single
  trigger:
    - platform: time
      at: 08:30
  condition:
    - condition: state
      entity_id: group.presence_home
      state: home
  action:
    - scene: scene.morning
