- alias: "Active room - office"
  trigger:
    - platform: state
      entity_id: input_select.active_room
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.active_room
              state: "office"
          sequence:
            - action: climate.set_temperature
              target:
                entity_id: climate.server_cabinet
              data:
                temperature: 30
            - action: switch.turn_on
              target:
                entity_id: switch.office
      default:
        - action: climate.set_temperature
          target:
            entity_id: climate.server_cabinet
          data:
            temperature: 25
