- alias: "Adaptive lighting"
  mode: single
  trigger:
    - platform: time_pattern
      minutes: "*"
  action:
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_lighting
        lights:
          - group.bedroom_lights
          - group.office_lights
          - group.living_room_lights
        adapt_color: true
        adapt_brightness: false
        turn_on_lights: false
        transition: 1
