- alias: "AC on"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - input_boolean.ac
      to: "on"
  action:
    - repeat:
        until:
          - condition: numeric_state
            entity_id: sensor.aircon_energy_power
            above: 100
        sequence:
          - service: remote.send_command
            data:
              device: aircon
              command: power
            target:
              entity_id: remote.broadlink_rm_mini_3
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - sensor.aircon_energy_power
            timeout: "00:00:30"
          - delay: 10
    - service: notify.dan
      data:
        title: ❄️ AC ❄️
        message: Switched on
        data:
          channel: "AC"
          notification_icon: "mdi:air-conditioner"

- alias: "AC off"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - input_boolean.ac
      to: "off"
  action:
    - repeat:
        until:
          - condition: numeric_state
            entity_id: sensor.aircon_energy_power
            below: 100
        sequence:
          - service: remote.send_command
            data:
              device: aircon
              command: power
            target:
              entity_id: remote.broadlink_rm_mini_3
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - sensor.aircon_energy_power
            timeout: "00:00:30"
          - delay: 10
    - service: notify.dan
      data:
        title: ❄️ AC ❄️
        message: Switched off
        data:
          channel: "AC"
          notification_icon: "mdi:air-conditioner"

- alias: "AC up"
  mode: single
  trigger:
    - platform: state
      entity_id: input_button.living_room_ac_up
  action:
    - service: remote.send_command
      data:
        device: aircon
        command: up
      target:
        entity_id: remote.broadlink_rm_mini_3

- alias: "AC down"
  mode: single
  trigger:
    - platform: state
      entity_id: input_button.living_room_ac_down
  action:
    - service: remote.send_command
      data:
        device: aircon
        command: down
      target:
        entity_id: remote.broadlink_rm_mini_3
