- alias: "Amplifier changed"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tv

      # https://www.home-assistant.io/docs/automation/trigger/#state-trigger
      # Trigger on all *state* changes, but not attributes, by setting to to null.
      # Otherwise, volume changes trigger the automation!
      to:
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: switch.amplifier
