- alias: "Amplifier changed"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.shield
              state: "off"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.amplifier
      default:
        - service: switch.turn_on
          target:
            entity_id: switch.amplifier
