- alias: "Amplifier changed"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.tv
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: switch.amplifier
