- alias: Backup to Sinkhole
  mode: single
  trigger:
    - platform: state
      entity_id: switch.sinkhole
      from: "off"
      to: "on"
      for:
        minutes: 30
  action:
    - service: hassio.backup_full
      data:
        compressed: false
