- alias: Backup every Sunday
  mode: single
  trigger:
    platform: time
    at: "03:00:00"
  condition:
    condition: time
    weekday:
      - sun
  action:
    - service: rest_command.healthcheck_start
      data:
        ping_key: !secret hc_ping_key
        slug: "home-assistant-backup"
    - service: hassio.backup_full
      data:
        compressed: true
    - service: rest_command.healthcheck_finish
      data:
        ping_key: !secret hc_ping_key
        slug: "home-assistant-backup"
