- alias: "Barn AC off at sunset"
  mode: single
  triggers:
    - trigger: sun
      event: sunset
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.barn_ac

- alias: "Barn AC on at sunrise"
  mode: single
  triggers:
    - trigger: sun
      event: sunrise
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.barn_ac
