- alias: Battery control
  trigger:
    - platform: state
      entity_id: input_select.battery_mode
    - platform: time_pattern
      minutes: "/10"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.battery_mode
              state: "Idle"
          sequence:
            - service: script.toggle_enphase_charge_from_grid
              data:
                enabled: "false"
            - delay: "00:00:01"
            - service: script.toggle_enphase_discharge_to_grid
              data:
                enabled: "false"

        - conditions:
            - condition: state
              entity_id: input_select.battery_mode
              state: "Charge"
          sequence:
            - service: script.toggle_enphase_charge_from_grid
              data:
                enabled: "true"
            - delay: "00:00:01"
            - service: script.toggle_enphase_discharge_to_grid
              data:
                enabled: "false"

        - conditions:
            - condition: state
              entity_id: input_select.battery_mode
              state: "Discharge"
          sequence:
            - service: script.toggle_enphase_charge_from_grid
              data:
                enabled: "false"
            - delay: "00:00:01"
            - service: script.toggle_enphase_discharge_to_grid
              data:
                enabled: "true"
