- alias: "Battery: off peak"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      to: null
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
              state: "on"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.battery_charge
      default:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.battery_charge
