- alias: Battery schedule
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.battery
  action:
    choose:
      - conditions:
          - condition: state
            entity_id: schedule.battery
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: input_boolean.battery_charge
      - conditions:
          - condition: state
            entity_id: schedule.battery
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: input_boolean.battery_charge
