- alias: "Battery: off peak"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
  action:
    - service: >
        {% if is_state('binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak', 'on') %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      target:
        entity_id: input_boolean.battery_charge
