- alias: Battery control
  trigger:
    - platform: state
      entity_id: input_boolean.battery_charge
    - platform: time_pattern
      minutes: "/10"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.battery_charge
              state: "off"
          sequence:
            - service: script.toggle_enphase_charge_from_grid
              data:
                enabled: "false"

        - conditions:
            - condition: state
              entity_id: input_boolean.battery_charge
              state: "on"
          sequence:
            - service: script.toggle_enphase_charge_from_grid
              data:
                enabled: "true"
