- alias: Battery schedule
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.battery
  action:
    choose:
      - conditions:
          - condition: state
            entity_id: schedule.battery
            state: "on"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.battery_mode
            data:
              option: "{{ state_attr('schedule.battery', 'state') }}"
      - conditions:
          - condition: state
            entity_id: schedule.battery
            state: "off"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.battery_mode
            data:
              option: "Idle"
