- alias: "Battery: free electricity sessions"
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
      to: null
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
              state: "on"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.battery_charge
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
              state: "off"
          sequence:
            - service: input_boolean.turn_off
              target:
                entity_id: input_boolean.battery_charge
