- alias: "Charge on peaktime cheap rate power"
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_cheap_rate
      to:
        - "on"
        - "off"
    - platform: state
      entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
      to:
        - "on"
        - "off"
  condition:
    - condition: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      state: "off"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_cheap_rate
              state: "on"
          sequence:
            - service: input_select.select_option
              target:
                entity_id: input_select.battery_mode
              data:
                option: "Charge"
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
              state: "on"
          sequence:
            - service: input_select.select_option
              target:
                entity_id: input_select.battery_mode
              data:
                option: "Charge"
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_cheap_rate
              state: "off"
            - condition: state
              entity_id: binary_sensor.octopus_energy_a_fad3b08a_octoplus_free_electricity_session
              state: "off"
          sequence:
            - service: input_select.select_option
              target:
                entity_id: input_select.battery_mode
              data:
                option: "Idle"
