- alias: Conservatory dehumidifier control
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
              state: "on"
          sequence:
            - action: humidifier.set_humidity
              target:
                entity_id: humidifier.dehumidifier
              data:
                # Set to the Off-Peak value
                humidity: "{{ states('input_number.dehumidifier_offpeak') | int }}"
      default:
        - action: humidifier.set_humidity
          target:
            entity_id: humidifier.dehumidifier
          data:
            humidity: "{{ states('input_number.dehumidifier_peak') | int }}"
