- alias: "Custom actions based on active room"
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_room
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.active_room
              state: "conservatory"
          sequence:
            - service: humidifier.turn_off
              entity_id: humidifier.conservatory_dehumidifier
        - conditions:
            - condition: state
              entity_id: input_select.active_room
              state: "bedroom"
          sequence:
            - service: switch.turn_on
              entity_id: switch.bed_light_power
      default:
        - service: humidifier.turn_on
          entity_id: humidifier.conservatory_dehumidifier
