- alias: "Dehumidifier: Peak"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - service: humidifier.set_humidity
      data:
        humidity: >
          {{ states("input_number.dehumidifier_peak") | float }}
      target:
        entity_id: humidifier.conservatory_dehumidifier

- alias: "Dehumidifier: Off-peak"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - service: humidifier.set_humidity
      data:
        humidity: >
          {{ states("input_number.dehumidifier_offpeak") | float }}
      target:
        entity_id: humidifier.conservatory_dehumidifier

- alias: "Dehumidifier: Full"
  trigger:
    - platform: numeric_state
      entity_id: sensor.dehumidifier_energy_power
      below: 50
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: switch.dehumidifier
      state: "on"
  action:
    - service: notify.dan
      data:
        title: "Dehumidifier Full"
        message: "Power below 50W for 10 minutes"
        data:
          channel: "dehumidifier"
          notification_icon: "mdi:water-alert"
