- alias: "Door: open"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opening
      to: "on"
  action:
    - service: notify.dan
      data:
        message: "Door opened at {{ now().strftime('%H:%M') }}"
- alias: "Door: closed"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opening
      to: "off"
  action:
    - service: notify.dan
      data:
        message: "Door opened at {{ now().strftime('%H:%M') }}"
