- alias: Enable central heating
  mode: single
  trigger:
    - platform: state
      entity_id: input_button.enable_central_heating
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.central_heating
      data:
        hvac_mode: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.central_heating
      data:
        temperature: >
          {{ states("input_number.thermostat_high") | float }}
