- alias: "Update Enphase Schedule on Energy Intents Change"
  description: "Triggers when sensor.energy_intents changes and updates the Enphase schedule."
  trigger:
    - platform: state
      entity_id: sensor.energy_intents
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.envoy_122322027694_available_battery_energy
          state: unavailable
  action:
    - service: script.enphase_delete_schedule
      data:
        schedule_type: "all"
    - service: notify.dan
      data:
        title: "Updating..."
        message: "Deleted existing schedules"
        data:
          notification_icon: "mdi:battery-sync"
          channel: "energy_intents_schedule"
          tag: energy_intents_schedule
    - delay: "00:00:02"
    - variables:
        simplified_events: >
          {% set events = state_attr('sensor.energy_intents', 'events') or [] %}
          [
            {% for event in events %}
              {% if event.start and event.end %}
                {% set start_dt = as_datetime(event.start) %}
                {% set end_dt = as_datetime(event.end) %}
                {
                  'start_time': '{{ start_dt.strftime('%H:%M') }}',
                  'end_time': '{{ end_dt.strftime('%H:%M') }}',
                  'weekday': {{ start_dt.weekday() + 1 }},
                  'schedule_type': '{{ 'CFG' if event.intent == 'Charge' else 'DTG' }}',
                  'limit': {{ 100 if event.intent == 'Charge' else 6 }}
                }{% if not loop.last %},{% endif %}
              {% endif %}
            {% endfor %}
          ]
    - repeat:
        for_each: "{{ simplified_events }}"
        sequence:
          - service: script.enphase_add_schedule
            data:
              start_time: "{{ repeat.item.start_time }}"
              end_time: "{{ repeat.item.end_time }}"
              schedule_type: "{{ repeat.item.schedule_type }}"
              days: "{{ [repeat.item.weekday] | string }}"
              limit: "{{ repeat.item.limit }}"
          - service: notify.dan
            data:
              title: "Updating..."
              message: Added schedule from {{ repeat.item.start_time }} to {{ repeat.item.end_time }}
              data:
                notification_icon: "mdi:battery-sync"
                channel: "energy_intents_schedule"
                tag: energy_intents_schedule
          - delay: "00:00:01"
    - service: script.toggle_enphase_charge_from_grid
      data:
        charge: "true"
    - service: notify.dan
      data:
        title: "Updating..."
        message: "Enabled charge"
        data:
          notification_icon: "mdi:battery-sync"
          channel: "energy_intents_schedule"
          tag: energy_intents_schedule
    - delay: "00:00:01"
    - service: script.toggle_enphase_discharge_to_grid
      data:
        discharge: "true"
    - service: notify.dan
      data:
        title: "Updating..."
        message: "Enabled discharge"
        data:
          notification_icon: "mdi:battery-sync"
          channel: "energy_intents_schedule"
          tag: energy_intents_schedule
    - service: notify.dan
      data:
        title: "Energy schedule updated"
        data:
          notification_icon: "mdi:battery-check"
          channel: "energy_intents_schedule"
          tag: energy_intents_schedule
        message: >
          {% set events = state_attr('sensor.energy_intents', 'events') or [] %}
          {% if events %}
            {% for event in events %}
              {% if event.start and event.end %}
                {% set start_dt = as_datetime(event.start) %}
                {% set end_dt = as_datetime(event.end) %}
                {% set day_name = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][start_dt.weekday()] %}
                • {{ day_name }} {{ start_dt.strftime('%H:%M') }}-{{ end_dt.strftime('%H:%M') }}: {{ event.intent }}
              {% endif %}
            {% endfor %}
          {% else %}
            No energy intents events found.
          {% endif %}

  mode: single
