- alias: "Energy price: changed"
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate
      to: null
  action:
    - service: notify.dan
      data:
        title: "{{ states('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate') | float | round(4) * 100 }} p/kWh"
        message: "{{now().hour}}:{{now().minute}}"
        data:
          channel: "Energy price"
          tag: "energy-price" # This is used to replace notifications
          notification_icon: "mdi:lightning-bolt"
          importance: "min"
