- alias: "Energy price: changed"
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate
      to: null
  variables:
    prev: "{{
    states('sensor.octopus_energy_electricity_20j0046498_2000052144657_previous_rate')
    | float * 100 }}"
    current: "{{
    states('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate')
    | float * 100 }}"
    next: "{{
    states('sensor.octopus_energy_electricity_20j0046498_2000052144657_next_rate')
    | float * 100 }}"
  action:
    - service: notify.dan
      data:
        title: "{{ current | round(2) }} p/kWh @ {{ now().timestamp() | timestamp_custom('%H:%M') }}"
        message: "
          {{ '↑' if current < prev else '↓' }} Previous: {{ prev | round(2) }} p/kWh<br>
          {{ '↑' if current < next else '↓' }}  Next: {{ next | round(2) }} p/kWh"
        data:
          channel: "Energy price"
          tag: "energy-price" # This is used to replace notifications
          notification_icon: "mdi:lightning-bolt"
          importance: "min"


- alias: "Energy price: daily rates updated"
  mode: single
  trigger:
    - platform: state
      # {{
      # state_attr('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate',
      # 'current_day_average_rate') }}
      entity_id: sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate
      attribute: current_day_average_rate
  variables:
    min: "{{
    state_attr('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate', 'current_day_min_rate')
    | round(2) }}"
    max: "{{
    state_attr('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate', 'current_day_max_rate')
    | round(2) }}"
    avg: "{{
    state_attr('sensor.octopus_energy_electricity_20j0046498_2000052144657_current_rate', 'current_day_average_rate')
    | round(2) }}"
  action:
    - service: notify.dan
      data:
        title: "Rates published"
        message: "{{ min }}-{{ max }}p (avg: {{ avg }}p)"
        data:
          channel: "Rates published"
          tag: "rates-published"
          notification_icon: "mdi:lightning-bolt"
          importance: "min"
