- alias: Front Door Light Motion
  mode: restart
  trigger:
    - platform: event
      event_type: front_door_motion
  action:
    - service: light.turn_on
      target:
        entity_id: light.front_door_light
    - delay: "00:05:00"
    - service: light.turn_off
      target:
        entity_id: light.front_door_light
