- alias: Front door light toggles motion detection
  mode: single
  trigger:
    - platform: state
      entity_id: light.front_door_light
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.front_door_light
              state: "on"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.front_door_motion_detection
        - conditions:
            - condition: state
              entity_id: light.front_door_light
              state: "off"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.front_door_motion_detection

- alias: Auto enable motion detection at 6am
  mode: single
  trigger:
    - platform: time
      at: "06:00:00"
  condition:
    - condition: state
      entity_id: switch.front_door_motion_detection
      state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.front_door_motion_detection
    - service: notify.dan
      data:
        message: "Front door motion detection enabled"
        title: "Motion Detection"
