- alias: "Garden lights on"
  mode: single
  conditions:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  triggers:
    - trigger: state
      entity_id: binary_sensor.back_door_opening
      to: "on"
  actions:
    - action: light.turn_on
      target:
        entity_id: light.garden_lighting

- alias: "Garden lights off"
  triggers:
    - trigger: state
      entity_id: binary_sensor.back_door_opening
      to: "off"
      for:
        minutes: 5
  actions:
    - action: light.turn_off
      target:
        entity_id: light.garden_lighting
