- alias: "Hallway: Morning lamp off"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor_occupancy
      to: "on"
    - platform: state
      entity_id: binary_sensor.landing_motion_sensor_opening
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
      before: "09:00:00"
  action:
    - action: light.turn_off
      target:
        entity_id: light.bedroom_lamp_left
