- alias: "Heating schedule: Normal"
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.heating
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.automations
      state: "on"
    - condition: state
      entity_id: group.presence_home
      state: home
  action:
    - service: climate.set_temperature
      data:
        temperature: 18
      target:
        entity_id: climate.thermostat

- alias: "Heating schedule: Low"
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.heating
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - service: climate.set_temperature
      data:
        temperature: 15
      target:
        entity_id: climate.thermostat
