- alias: "Heating schedule: Normal"
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.heating
      to: "on"
  condition:
    - condition: state
      entity_id: group.presence_home
      state: home
  action:
    - service: climate.set_temperature
      data:
        temperature: >
          {{ states("input_number.thermostat_high") | float }}
      target:
        entity_id: climate.virtual_central_heating

- alias: "Heating schedule: Low"
  mode: single
  trigger:
    - platform: state
      entity_id: schedule.heating
      to: "off"
  action:
    - service: climate.set_temperature
      data:
        temperature: >
          {{ states("input_number.thermostat_low") | float }}
      target:
        entity_id: climate.virtual_central_heating
