- alias: "Heating sync"
  trigger:
    - platform: state
      entity_id: input_select.heating_mode
  action:
    - service: climate.set_preset_mode
      data_template:
        preset_mode: "{{ trigger.to_state.state }}"
      target:
        entity_id: group.thermostats
