- alias: "Hot water boost"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.hot_water_boost
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hot_water_boost
  action:
    - choose:
        - conditions: "{{ trigger.event.event_type == 'timer.started' }}"
          alias: "Start"
          sequence:
            - service: homeassistant.turn_on
              target:
                entity_id: light.water_heater
        - conditions: "{{ trigger.event.event_type == 'timer.finished' }}"
          alias: "Stop"
          sequence:
            - service: homeassistant.turn_off
              target:
                entity_id: light.water_heater
