- alias: "Living room dining room table button"
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:12:4b:00:22:cf:67:01
        command: toggle
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.active_room
      data:
        option: "living_room"
