- alias: "Movie mode activate"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: "playing"
  condition:
    condition: state
    entity_id: media_player.shield
    attribute: app_name
    state:
      - "Netflix"
      - "Plex"
      - "Prime Video"
      - "VLC"
  action:
    - scene: scene.movie_mode
