- alias: "Movie mode - activate"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: "playing"
  condition:
    condition: state
    entity_id: media_player.shield
    attribute: app_name
    state:
      - "Netflix"
      - "Plex"
      - "Prime Video"
      - "VLC"
  action:
    - scene: scene.movie_mode

- alias: "Movie mode - deactivate"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: "paused"
      for:
        seconds: 5 # Account for fast-forwarding and rewinding
  condition:
    condition: state
    entity_id: media_player.shield
    attribute: app_name
    state:
      - "Netflix"
      - "Plex"
      - "Prime Video"
      - "VLC"
  action:
    - service: light.turn_on
      target:
        entity_id: light.living_room_lights
      data:
        brightness: 255
