- alias: "Movie mode - activate"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield_android_tv
      attribute: app_name
      to: "com.plexapp.android"
  condition:
    - condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - scene: scene.movie_mode
