- alias: "Movie mode - activate"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.shield_android_tv
      attribute: app_name
      to: "org.jellyfin.androidtv"
  action:
    - scene: scene.movie_mode
