- alias: "Office AC when active room is office"
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_room
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.active_room
              state: "office"
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.office_ac
              data:
                hvac_mode: cool
            - service: climate.set_preset_mode
              target:
                entity_id: climate.office_ac
              data:
                preset_mode: quiet
            - service: climate.set_temperature
              target:
                entity_id: climate.office_ac
              data:
                temperature: "{{ states('input_number.office_ac_default_temp') | float }}"
      default:
        - service: climate.turn_off
          target:
            entity_id: climate.office_ac
