- alias: "Office switch on when battery low"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.river_2_max_discharge_remaining_time
      below: 10
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.office
