- alias: "Office motion light control"
  mode: single
  triggers:
    - trigger: state
      entity_id: binary_sensor.apollo_msr_2_1517ac_radar_still_target
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.apollo_msr_2_1517ac_radar_still_target
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.apollo_msr_2_1517ac_rgb_light
        - conditions:
            - condition: state
              entity_id: binary_sensor.apollo_msr_2_1517ac_radar_still_target
              state: "off"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.apollo_msr_2_1517ac_rgb_light
