- alias: "Off peak: Changed"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.off_peak
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: group.off_peak
