- alias: "Off peak: Changed"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.off_peak
  condition:
    alias: "State is valid"
    condition: template
    value_template: "{{ trigger.to_state.state != 'unavailable'}}"
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: group.off_peak
