- alias: "Everything off -> Media players off"
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.everything_off
      domain: scene
      service: turn_on
  action:
    service: media_player.turn_off
    entity_id: all
