- alias: "Leave home"
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_room
      to: "out"
  action:
    - scene: scene.lights_off
    - service: media_player.turn_off
      entity_id: all
