- alias: "Plex playing -> Movie mode"
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      to: "playing"
  action:
    - scene: scene.movie_mode
