- alias: "Power drain: started"
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.power_drain
      from: "off"
      to: "on"
  action:
    - service: notify.dan
      data:
        title: ⚡ Draining power ⚡
        message: Maximum power drain started
        data:
          notification_icon: "mdi:home-lightning-bolt-outline"
    - service: input_select.select_option
      target:
        entity_id: input_select.heating_mode
      data:
        option: activity
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.living_room
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.ac

- alias: "Power drain: ended"
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.power_drain
      from: "on"
      to: "off"
  action:
    - service: notify.dan
      data:
        title: ⚡ No longer draining power ⚡
        message: Maximum power drain ended
        data:
          notification_icon: "mdi:home-lightning-bolt-outline"
    - service: input_select.select_option
      target:
        entity_id: input_select.heating_mode
      data:
        option: away
    - service: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.living_room
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.ac
