- alias: "Arrive home (lights)"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: "on"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: "above_horizon"
          sequence:
            - scene: scene.day_mode
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: "below_horizon"
          sequence:
            - scene: scene.everything_on

- alias: "Leave home (lights)"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: home
      to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: "on"
  action:
    - scene: scene.everything_off

- alias: "Arrive home (heating)"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: input_boolean.heating_automations
      state: "on"
    - condition: state
      entity_id: binary_sensor.octopus_energy_saving_session
      state: "off"
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: group.thermostats
      data:
        hvac_mode: "heat"

- alias: "Leave home (heating)"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: home
      to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.heating_automations
      state: "on"
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: group.thermostats
      data:
        hvac_mode: "off"

- alias: "Arrive home (kettle)"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: binary_sensor.octopus_energy_saving_session
      state: "off"
    - condition: state
      entity_id: switch.kettle
      state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.kettle
    - service: notify.dan
      data:
        title: 🫖 Kettle 🫖
        message: Switched on
        data:
          channel: "Kettle"
          notification_icon: "mdi:kettle"
