- alias: "Arrive: lights"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.presence_automations
      state: "on"
  action:
    - scene: scene.everything_on

- alias: "Arrive: notify"
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: input_boolean.presence_automations
      state: "on"
  action:
    - service: notify.dan
      data:
        message: Arrived home

- alias: Leave home
  mode: single
  trigger:
    - platform: state
      entity_id: group.presence_home
      from: home
      to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.presence_automations
      state: "on"
  action:
    - scene: scene.everything_off
    - service: notify.dan
      data:
        message: Away mode
