- alias: Printer progress
  mode: single
  triggers:
    - trigger: state
      entity_id: sensor.a1_print_progress
      from: null
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.a1_current_stage
              state: "printing"
          sequence:
            - service: notify.dan
              data:
                title: "Print finishes at {{ as_timestamp(states('sensor.a1_end_time')) | timestamp_custom('%H:%M') }}"
                message: "{{ states('sensor.a1_print_progress') }}% complete"
                data:
                  channel: "printer"
                  tag: printer
                  notification_icon: "mdi:printer-3d"
                  image: /api/image_proxy/image.a1_cover_image
                  progress: "{{ states('sensor.a1_print_progress') }}"
                  progress_max: 100
        - conditions:
            - condition: state
              entity_id: sensor.a1_current_stage
              state: "idle"
          sequence:
            - service: notify.dan
              data:
                title: "Printer idle"
                # https://companion.home-assistant.io/docs/notifications/notifications-basic/#clearing
                message: "clear_notification"
                data:
                  channel: "printer"
                  tag: printer
                  notification_icon: "mdi:printer-3d"
                  progress: -1
                  progress_max: 100
      default:
        - service: notify.dan
          data:
            title: "{{ states('sensor.a1_print_progress') }}% complete"
            message: "{{ states('sensor.a1_current_stage') }}"
            data:
              channel: "printer"
              tag: printer
              notification_icon: "mdi:printer-3d"
              image: /api/image_proxy/image.a1_cover_image

- alias: Printer fan
  # Turn on fan.tower_fan when sensor.a1_print_status is "printing"
  # and turn off when sensor.a1_print_status is "idle"
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.a1_print_status
      from: null
      to: null
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.a1_print_status
              state: "printing"
          sequence:
            - service: fan.turn_on
              target:
                entity_id: fan.tower_fan
        - conditions:
            - condition: state
              entity_id: sensor.a1_print_status
              state: "idle"
          sequence:
            - service: fan.turn_off
              target:
                entity_id: fan.tower_fan
      default: []
