- alias: "Office switch on when off peak starts"
  mode: single
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.office
