- alias: "Office switch control"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
    - platform: state
      entity_id: sensor.river_2_max_battery_level
  action:
    - choose:
        # Off-peak starts → turn on
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
              state: "on"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.office

        # Peak hours & battery <10% → turn on
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
              state: "off"
            - condition: numeric_state
              entity_id: sensor.river_2_max_battery_level
              below: 10
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.office

        # Peak hours & battery >20% → turn off
        - conditions:
            - condition: state
              entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
              state: "off"
            - condition: numeric_state
              entity_id: sensor.river_2_max_battery_level
              above: 20
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.office
