- alias: "Sunset actions"
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      # 30 minutes after sunset
      offset: "00:30:00"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.curtains
    - service: light.turn_on
      target:
        entity_id: light.front_door_light
