- alias: "Sunset: Lights on"
  mode: single
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - scene: scene.everything_on

- alias: "Midnight: Lights off if out"
  mode: single
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
    - condition: state
      entity_id: group.presence_home
      state: not_home
    - condition: state
      entity_id: input_boolean.presence_automations
      state: "on"
  action:
    - scene: scene.everything_off
    - service: notify.dan
      data:
        message: Lights turned off
