- alias: "Close curtains at sunset"
  mode: single
  triggers:
    - trigger: sun
      event: sunset
      # 30 minutes after sunset
      offset: "00:30:00"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.curtains
