- alias: Morning lights
  mode: single
  trigger:
    - platform: time
      at: sensor.pixel_8_next_alarm
  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: home
    - alias: "Automations enabled"
      condition: state
      entity_id: input_boolean.automations
      state: "on"
    - alias: "Alarm is triggered by Clock"
      condition: state
      entity_id: sensor.pixel_8_next_alarm
      attribute: package
      state: com.google.android.deskclock
  action:
    - alias: "Turn on bedroom lights"
      service: light.turn_on
      target:
        entity_id: light.bedroom_lights
      data:
        brightness_pct: 100
