- alias: Wake up lights
  mode: single
  trigger:
    - platform: time
      at: input_datetime.wake_up
  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: home
    - alias: "Automations enabled"
      condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - alias: "Turn on bedroom lights"
      service: light.turn_on
      target:
        entity_id: light.bedroom_lights
      data:
        brightness_pct: 100

- alias: Lights out
  mode: single
  trigger:
    - platform: time
      at: input_datetime.lights_out
  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: home
    - alias: "Automations enabled"
      condition: state
      entity_id: input_boolean.automations
      state: "on"
  action:
    - alias: "Turn off TV light"
      service: light.turn_off
      target:
        entity_id: light.tv_light
