- alias: UPS - notify when running
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_battery_runtime
  condition:
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
  action:
    - service: notify.dan
      data:
        title: "Homelab UPS discharging"
        message: "{{ states('sensor.homelab_ups_battery_charge')}}% remaining"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:battery-clock"

- alias: UPS - notify when online
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_status_data
      to: "OL"
  action:
    - service: notify.dan
      data:
        title: "Homelab UPS is online"
        message: "The UPS has switched back to grid power"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:power-plug"
