- alias: Homelab UPS notification
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_battery_runtime
  condition:
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
  action:
    - service: notify.dan
      data:
        title: "Homelab is on UPS power"
        message: "Battery runtime is {{ states('sensor.homelab_ups_battery_runtime') }} minutes"
        data:
          notification_icon: "mdi:battery-clock"
