- alias: UPS - notify when running
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_battery_runtime
  condition:
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
  action:
    - service: notify.dan
      data:
        title: "Homelab UPS discharging"
        message: "{{ states('sensor.homelab_ups_battery_charge')}}% remaining"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:battery-clock"

- alias: UPS - restore power when battery is below 10%
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.homelab_ups_battery_charge
      below: 10
  condition:
    - condition: template
      value_template: >
        {{ states('sensor.homelab_ups_battery_charge') not in ['unknown', 'unavailable'] }}
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
    - condition: state
      entity_id: switch.homelab
      state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.homelab

- alias: UPS - notify when online
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_status_data
      to: "OL"
  action:
    - service: notify.dan
      data:
        title: "Homelab UPS is online"
        message: "The UPS has switched back to grid power"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:power-plug"
