- alias: UPS - notify when running
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.homelab_ups_battery_runtime
  condition:
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
  action:
    - service: notify.dan
      data:
        title: "Homelab is on UPS power"
        message: "{{ states('sensor.homelab_ups_battery_charge')}}% ({{ states('sensor.homelab_ups_battery_runtime') }} minutes) remaining"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:battery-clock"

- alias: UPS - switch off when offpeak ends
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      from: "on"
      to: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.homelab

- alias: UPS - reconnect to grid when 10 minutes remaining
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.homelab_ups_battery_runtime
      below: 10
  condition:
    - condition: state
      entity_id: sensor.homelab_ups_status_data
      state: "OB DISCHRG"
    - condition: state
      entity_id: switch.homelab
      state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.homelab
    - service: notify.dan
      data:
        title: "Homelab UPS power restored"
        message: "Power has been restored to the Homelab"
        data:
          channel: "ups"
          tag: ups
          notification_icon: "mdi:power-plug"
