- alias: "Vacuum drying timer"
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - vacuum.robovac_x10_pro_omni
      to: docked
  actions:
    - action: timer.start
      target:
        entity_id: timer.robot_vacuum_drying
      data:
        duration: "02:00:00"
