- alias: "Notify when vacuum charged"
  mode: single
  trigger:
    - platform: state
      entity_id: vacuum.dumpster_fire
      attribute: battery_level
      to: "100"
  action:
    - service: notify.dan
      data:
        message: Vacuum charged
        data:
          notification_icon: "mdi:robot-vacuum"
