- alias: "Video call: started"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.dan_s_work_laptop_camera_in_use
      to: "on"
  condition:
    - condition: state
      entity_id: sensor.dan_s_work_laptop_ssid
      state: "irulan"
  action:
    - service: light.turn_on
      data:
        brightness: 255
      target:
        entity_id: light.elgato_keylight

- alias: "Video call: ended"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.dan_s_work_laptop_camera_in_use
      to: "off"
  condition:
    - condition: state
      entity_id: sensor.dan_s_work_laptop_ssid
      state: "irulan"
  action:
    - service: light.turn_off
      target:
        entity_id: light.elgato_keylight
