- alias: Wake up lights (Katie)
  mode: single
  trigger:
    - platform: time
      at: input_datetime.wake_up_katie
  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: home
    - alias: "Automations enabled"
      condition: state
      entity_id: input_boolean.automations
      state: "on"
    - alias: "Enabled"
      condition: state
      entity_id: input_boolean.wake_up_katie_enabled
      state: "on"
  action:
    - alias: "Turn on lamp"
      service: light.turn_on
      target:
        entity_id: light.bedroom_lamp_left
      data:
        brightness: 125

- alias: Wake up lights (Dan)
  mode: single
  trigger:
    - platform: time
      at: input_datetime.wake_up_dan
  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: home
    - alias: "Automations enabled"
      condition: state
      entity_id: input_boolean.automations
      state: "on"
    - alias: "Enabled"
      condition: state
      entity_id: input_boolean.wake_up_dan_enabled
      state: "on"
  action:
    - alias: "Turn on lamp"
      service: light.turn_on
      target:
        entity_id: light.bedroom_lamp_right
      data:
        brightness: 125
