- alias: "Washing machine finished"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.pm_energy_power
      below: 3
      for: "00:03:00"
  action:
    - service: notify.dan
      data:
        message: Washing machine finished
