- alias: "Turn off bedside lamps based on wireless charging devices"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.pixel_9_charger_type
        - sensor.pixel_7a_charger_type
      to: "wireless"

  condition:
    - alias: "Home"
      condition: state
      entity_id: group.presence_home
      state: "home"
    - condition: time
      after: "21:00:00"
      before: "01:00:00"

  action:
    - choose:
        - alias: "Pixel 9 only charging"
          conditions:
            - condition: state
              entity_id: sensor.pixel_9_charger_type
              state: "wireless"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.pixel_7a_charger_type
                  state: "wireless"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.bedtime_right_off

        - alias: "Pixel 7a only charging"
          conditions:
            - condition: state
              entity_id: sensor.pixel_7a_charger_type
              state: "wireless"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.pixel_9_charger_type
                  state: "wireless"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.bedtime_left_off

        - alias: "Both Pixel 9 and Pixel 7a charging"
          conditions:
            - condition: state
              entity_id: sensor.pixel_9_charger_type
              state: "wireless"
            - condition: state
              entity_id: sensor.pixel_7a_charger_type
              state: "wireless"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.lights_off
