# Automation to put Zappi in fast mode when battery energy is below export threshold
- alias: "Zappi to fast mode battery below export threshold"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.envoy_122322027694_available_battery_energy
        - select.myenergi_zappi_charge_mode
  condition:
    - alias: "Battery energy below threshold"
      condition: template
      value_template: "{{ states('sensor.envoy_122322027694_available_battery_energy') | float < states('input_number.battery_energy_zappi_threshold') | float }}"
    - alias: "Zappi currently stopped"
      condition: state
      entity_id: select.myenergi_zappi_charge_mode
      state: "Stopped"
  action:
    - service: select.select_option
      target:
        entity_id: select.myenergi_zappi_charge_mode
      data:
        option: "Fast"

# Automation to stop Zappi when off-peak period ends
- alias: "Zappi stop when off-peak ends"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.octopus_energy_electricity_15p0706167_2000050773706_off_peak
      to: "off"
  action:
    - service: select.select_option
      target:
        entity_id: select.myenergi_zappi_charge_mode
      data:
        option: "Stopped"
