- alias: "Zappi control"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.current_energy_intent
        - select.myenergi_zappi_charge_mode
        - switch.octopus_energy_00000000_0002_4000_8020_00000008191c_intelligent_smart_charge
  action:
    - choose:
        - alias: "ID3 Smart Charge"
          conditions:
            - alias: "ID3 smart charge enabled"
              condition: state
              entity_id: switch.octopus_energy_00000000_0002_4000_8020_00000008191c_intelligent_smart_charge
              state: "on"
          sequence:
            - alias: "Set Zappi to Fast"
              service: select.select_option
              target:
                entity_id: select.myenergi_zappi_charge_mode
              data:
                option: "Fast"
        - alias: "Charge"
          conditions:
            - alias: "Current energy intent is Charge"
              condition: state
              entity_id: sensor.current_energy_intent
              state: "Charge"
            - alias: "Zappi currently stopped"
              condition: state
              entity_id: select.myenergi_zappi_charge_mode
              state: "Stopped"
          sequence:
            - alias: "Set Zappi to Fast"
              service: select.select_option
              target:
                entity_id: select.myenergi_zappi_charge_mode
              data:
                option: "Fast"
        - alias: "Stop"
          conditions:
            - alias: "Current energy intent is not Charge"
              condition: not
              conditions:
                - condition: state
                  entity_id: sensor.current_energy_intent
                  state: "Charge"
            - alias: "Zappi currently fast"
              condition: state
              entity_id: select.myenergi_zappi_charge_mode
              state: "Fast"
          sequence:
            - alias: "Set Zappi to Stopped"
              service: select.select_option
              target:
                entity_id: select.myenergi_zappi_charge_mode
              data:
                option: "Stopped"

- alias: "Notify Dan when Zappi plug state changes"
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.myenergi_zappi_plug_status
  action:
    - service: notify.mobile_app_pixel_9
      data:
        title: "Zappi"
        message: "{{ states('sensor.myenergi_zappi_plug_status') }}"
