# If Zoe is at home, and on charge, and battery is above the number input helper limit, then turn off the zappi
- alias: "Zoe charge limit - turn off zappi when battery above limit"
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.wp22lxc_battery
      to: null
  condition:
    - alias: "Zoe at home"
      condition: state
      entity_id: device_tracker.wp22lxc_location
      state: "home"
    - alias: "Zoe charging"
      condition: state
      entity_id: binary_sensor.wp22lxc_charging
      state: "on"
    - alias: "Battery above limit"
      condition: template
      value_template: "{{ states('sensor.wp22lxc_battery') | float > states('input_number.zoe_charge_limit') | float }}"
  action:
    - service: button.press
      target:
        entity_id: button.wp22lxc_stop_charge
